---
#hash, password_hash
- hosts: all
  gather_facts: no
  become: yes
  
  vars:
    - users:
        diane: password
        will: secret
    - cat: cat

  tasks:    
    - name: Create a group
      group:
        name: lab
        state: present

    - name: Create users
      user:
        groups: lab
        name: "{{ item.key }}"
        password: "{{ item.value | password_hash('sha256') }}"
      with_dict: "{{ users }}"

    - name: create a temp file
      file:
        state: touch
        path: /home/hash

    - name: Print a random hash into a file
      lineinfile:
        path: /home/hash
        line: "{{ cat | hash('sha256') }}"
