---
#try out templates
- hosts: all
  become: yes

  tasks:
  - name: Upload template number one
    template:
      src: ./templates/example.conf.j2
      dest: /home/example.conf

  - name: Upload template number two
    template:
      src: ./templates/config.j2
      dest: /home/config
      owner: root
      group: root
      mode: 0700
