---
- hosts: localhost

  tasks:
    - name: delegate facts to another server
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['webservers'] }}"

    - name: access these facts
      debug:
        msg: "{{ ansible_hostname }} is the delegated hostname of server {{ item }}"
      loop: "{{ groups['webservers'] }}"
