---
#trying out serial
- hosts: all
  become: yes
  gather_facts: no
  serial:
    - 1
    - 50%
  max_fail_percentage: 50%

  tasks:
  
  - name: Restart nginx service
    service:
      name: nginx
      state: restarted 

  - name: Fail a task for one server
    file:
      name: /tmp/fakedir/text.txt
      state: touch
    run_once: true

  - name: do yum update for rest
    yum:
      update_cache: yes
